### ISSUE TITLE
Rumps do not works on all taskbars.

### ISSUE THREAD

**Issue by fableman73** [itext/rups#37]
Problem: Rumps works great when I have an external screen connected, when I disconnect the external screen then rump is not showed up on the laptop screen.

If I start rumps without a external screen rumps still fails to show up on the laptop screen, but if I insert an external screen it shows up,

Computer: Mac M1,  (updated OS)

Requirement already satisfied: rumps in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.4.0)
Requirement already satisfied: pyobjc-framework-Cocoa in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rumps) (9.0)
Requirement already satisfied: pyobjc-core>=9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pyobjc-framework-Cocoa->rumps) (9.0)

**Comment by fableman73** [comment]
Update.. I closed  a secure endpoint application then then my rumps application showed on on the laptop screen.

Is there any kind of limit of icons on taskbar  that prevent rumps to show up?

**Comment by Minothor** [comment]
Sorry, but are you perhaps looking for: https://github.com/jaredks/rumps ?
This is the repository for iText RUPS, a PDF inspection tool written in Java rather than Python.
Warm regards and wishing you a belated Happy New Year.
